### ISSUE TITLE
RecyclerView 设置为 wrap_content 无效，下方有空白

### ISSUE THREAD

**Issue by xing16** [756718646/RichWebList#2]

**Comment by ghost** [comment]
NestedScrollView包裹webview和recyclerView完美解决问题.........为何要这个.....

**Comment by xing16** [comment]
> NestedScrollView包裹webview和recyclerView完美解决问题.........为何要这个.....

NestedScrollView 包裹RecyclerView 会导致 RecyclerView 没有复用 item,

**Comment by 756718646** [comment]
RecycleView最好不要设置wrap_content，直接设置match_parent，然后动态计算前面几个item，这样会有2种情况:1,直到前面几个item超过屏幕宽度,这个情况就是demo那样，2，另外一种情况就是需用根据item高度动态限制滑动伸缩（可以参考空布局的demo代码）

后续这个动态添加item和限制头部滑动，我单独做一个demo出来方便大家
